x-app: &app
  env_file:
    - ./.env
  restart: unless-stopped
  platform: linux/amd64

services:
  auth-postgres:
    image: postgres:14
    container_name: aledev-auth-postgres
    <<: *app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth_postgres_volume:/var/lib/postgresql/data/
    networks:
      auth-internal:
        aliases:
          - postgres
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"

  auth-redis:
    image: redis:6
    container_name: aledev-auth-redis
    <<: *app
    volumes:
      - auth_redis_volume:/data
    networks:
      auth-internal:
        aliases:
          - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-app:
    build:
      context: ./app
    container_name: aledev-auth-app
    <<: *app
    command: python src/main.py
    environment:
      UVICORN_RELOAD: "1"
      DB_PORT: ${DB_PORT:-5432}
    volumes:
      - ./app:/usr/src/app/
    networks:
      - auth-internal
    ports:
      - "8501:8000"
    depends_on:
      auth-redis:
        condition: service_healthy
      auth-postgres:
        condition: service_healthy


volumes:
  auth_postgres_volume:
  auth_redis_volume:

networks:
  auth-internal:
