x-app: &app
  env_file:
    - ./.env
  restart: always
  platform: linux/amd64

services:
  postgres:
    image: postgres:14
    container_name: aledev-portfolio-postgres
    <<: *app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"

  app:
    image: aleksioprime/aledev-portfolio:latest
    container_name: aledev-portfolio-app
    <<: *app
    command: python src/main.py
    volumes:
      - /root/aledev/media:/usr/src/app/media
    ports:
      - "8002:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_volume: