services:
  tunnel-gw:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: aledev-tunnel-gw
    restart: unless-stopped
    platform: linux/amd64
    environment:
      TZ: "Europe/Moscow"
      PUID: "0"
      PGID: "0"
      USER_NAME: "tunnel"
      PASSWORD_ACCESS: "false"
      SUDO_ACCESS: "false"
      PUBLIC_KEY_FILE: "/config/keys/home_server.pub"
    volumes:
      - /root/aledev/tunnel/config:/config
      - /root/aledev/tunnel/keys:/config/keys:ro
      - /root/aledev/tunnel/sshd_config.d:/config/sshd/sshd_config.d:ro
    ports:
      - "46222:2222"
      - "49222:9022"
    networks:
      - shared

networks:
  shared:
    external: true
    name: aledev-shared
