services:

  frontend-mysite:
    build:
      context: ./frontends/mysite
      target: dev
      args:
        - VITE_LOGGING=1
        - VITE_AUTH_URL=http://localhost:8501
        - VITE_PORTFOLIO_URL=http://localhost:8502
        - VITE_BLOG_URL=http://localhost:8503
    restart: always
    platform: linux/amd64
    container_name: aledev-frontend-mysite
    volumes:
      - ./frontends/mysite/app/src:/usr/src/app/src
    ports:
      - "8085:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"