x-app: &app
  env_file:
    - ./.env
  restart: no
  platform: linux/amd64

services:

  pgadmin:
    container_name: aledev-pgadmin
    image: dpage/pgadmin4:latest
    <<: *app
    ports:
      - "8085:80"
    volumes:
      - "data-pgadmin:/var/lib/pgadmin"

  frontend:
    build:
      context: ./frontend
      target: dev
      args:
        - VITE_LOGGING=1
        - VITE_AUTH_URL=http://localhost:8501
    <<: *app
    container_name: aledev-frontend
    volumes:
      - ./frontend/app/src:/usr/src/app/src
    ports:
      - "8080:5173"

volumes:
  data-pgadmin:
