x-app: &app
  env_file:
    - .env
  restart: always
  platform: linux/amd64

services:
  nginx:
    image: aleksioprime/aledev-frontend-nginx:latest
    container_name: aledev-nginx
    <<: *app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - /root/aledev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /root/aledev/mysite/media:/usr/share/nginx/html/mysite/media
      - /root/aledev/blog/media:/usr/share/nginx/html/blog/media
      - mysite_dist:/usr/share/nginx/html/mysite
      - blog_dist:/usr/share/nginx/html/blog
    depends_on:
      - frontend-mysite
      # - frontend-blog
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend-mysite:
    image: aleksioprime/aledev-frontend-mysite:latest
    container_name: aledev-frontend-mysite
    <<: *app
    volumes:
      - mysite_dist:/usr/src/app/dist

  # frontend-blog:
  #   image: aleksioprime/aledev-frontend-blog:latest
  #   container_name: aledev-frontend-blog
  #   <<: *app
  #   volumes:
  #     - blog_dist:/usr/src/app/dist

volumes:
  mysite_dist:
  blog_dist: