services:
  nginx:
    image: nginx:alpine
    container_name: aledev-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontends/mysite/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend-mysite
      - frontend-blog
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend-mysite:
    build:
      context: ./frontends/mysite
      target: dev
      args:
        - VITE_LOGGING=1
        - VITE_AUTH_URL=http://localhost:8501
        - VITE_PORTFOLIO_URL=http://localhost:8502
    restart: always
    platform: linux/amd64
    container_name: aledev-frontend-mysite
    volumes:
      - ./frontends/mysite/app/src:/usr/src/app/src
    ports:
      - "8085:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend-blog:
    build:
      context: ./frontends/blog
      target: dev
      args:
        - VITE_LOGGING=1
        - VITE_AUTH_URL=http://localhost:8501
        - VITE_BLOG_URL=http://localhost:8503
    restart: always
    platform: linux/amd64
    container_name: aledev-frontend-blog
    volumes:
      - ./frontends/blog/app/src:/usr/src/app/src
    ports:
      - "8086:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
