x-app: &app
  env_file:
    - ./.env
  restart: always
  platform: linux/amd64

services:

  pgadmin:
    container_name: aledev-pgadmin
    image: dpage/pgadmin4:latest
    <<: *app
    ports:
      - "8085:80"
    volumes:
      - "data-pgadmin:/var/lib/pgadmin"

  frontend:
    image: aleksioprime/aledev-frontend:latest
    container_name: aledev-frontend
    <<: *app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - /root/aledev/media:/usr/share/nginx/html/media
      - /root/aledev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

volumes:
  data-pgadmin:
