services:
  3xui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: aledev-3xui
    volumes:
      - /root/aledev/3xui/db/:/etc/x-ui/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
    tty: true
    network_mode: host
    restart: unless-stopped