"""init migration

Revision ID: 10865b216202
Revises: None
Create Date: 2026-09-29 14:16:30.851922

"""
from typing import Sequence, Union
from datetime import datetime, timezone
from uuid import UUID

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '10865b216202'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_category'), 'achievements', ['category'], unique=False)
    op.create_index(op.f('ix_achievements_scope'), 'achievements', ['scope'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('order', 'question', name='feedbackkind', native_enum=False, length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=30), nullable=True),
    sa.Column('budget', sa.String(length=30), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'done', 'archived', 'spam', name='feedbackstatus', native_enum=False, length=20), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('email_status', sa.Enum('pending', 'sending', 'sent', 'failed', name='emailstatus', native_enum=False, length=20), nullable=False),
    sa.Column('email_attempts', sa.Integer(), nullable=False),
    sa.Column('email_provider', sa.String(length=20), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_messages_created_at', 'feedback_messages', ['created_at'], unique=False)
    op.create_index('ix_feedback_messages_email_status', 'feedback_messages', ['email_status'], unique=False)
    op.create_index('ix_feedback_messages_status', 'feedback_messages', ['status'], unique=False)
    op.create_table('mentoring_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('stack', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('demo_url', sa.String(length=255), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievement_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('achievement_id', sa.Uuid(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'en', name='langenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('achievement_id', 'lang', name='_achievement_lang_uc')
    )
    op.create_index(op.f('ix_achievement_translations_achievement_id'), 'achievement_translations', ['achievement_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_project_id'), 'articles', ['project_id'], unique=True)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_table('experience_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'en', name='langenum'), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'lang', name='_experience_lang_uc')
    )
    op.create_index(op.f('ix_experience_translations_experience_id'), 'experience_translations', ['experience_id'], unique=False)
    op.create_table('mentoring_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=40), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['mentoring_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'key', name='_mentoring_metric_key_uc')
    )
    op.create_index(op.f('ix_mentoring_metrics_page_id'), 'mentoring_metrics', ['page_id'], unique=False)
    op.create_table('mentoring_page_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'en', name='langenum'), nullable=False),
    sa.Column('kicker', sa.String(length=255), nullable=False),
    sa.Column('title_start', sa.String(length=255), nullable=False),
    sa.Column('title_accent', sa.String(length=255), nullable=False),
    sa.Column('lead', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['mentoring_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'lang', name='_mentoring_page_lang_uc')
    )
    op.create_index(op.f('ix_mentoring_page_translations_page_id'), 'mentoring_page_translations', ['page_id'], unique=False)
    op.create_table('project_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'en', name='langenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'lang', name='_project_lang_uc')
    )
    op.create_index(op.f('ix_project_translations_project_id'), 'project_translations', ['project_id'], unique=False)
    op.create_table('article_tocs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('anchor', sa.String(length=255), nullable=True),
    sa.Column('order', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['article_tocs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_tocs_article_id'), 'article_tocs', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_tocs_parent_id'), 'article_tocs', ['parent_id'], unique=False)
    op.create_table('mentoring_metric_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'en', name='langenum'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['mentoring_metrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_id', 'lang', name='_mentoring_metric_lang_uc')
    )
    op.create_index(op.f('ix_mentoring_metric_translations_metric_id'), 'mentoring_metric_translations', ['metric_id'], unique=False)

    # Seed the current public portfolio content for a fresh database.
    lang_enum = postgresql.ENUM('ru', 'en', name='langenum', create_type=False)
    created_at = datetime(2026, 9, 29, tzinfo=timezone.utc)
    achievement_table = sa.table(
        'achievements',
        sa.column('id', sa.Uuid()), sa.column('category', sa.String()),
        sa.column('scope', sa.String()), sa.column('year', sa.Integer()),
        sa.column('source_url', sa.String()), sa.column('image_url', sa.String()),
        sa.column('order', sa.Integer()), sa.column('is_featured', sa.Boolean()),
        sa.column('is_published', sa.Boolean()), sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    achievement_translation_table = sa.table(
        'achievement_translations',
        sa.column('id', sa.Uuid()), sa.column('achievement_id', sa.Uuid()),
        sa.column('lang', lang_enum), sa.column('title', sa.String()),
        sa.column('organization', sa.String()), sa.column('result', sa.String()),
        sa.column('short_description', sa.String()), sa.column('description', sa.Text()),
    )
    achievement_rows = [
        ('grant', 'personal', 2019,
         ('Грантовый проект: платформа для изучения технического зрения', None, 'Грант', 'Мобильная платформа с нейросетями для распознавания дорожных знаков, испытательный полигон с 3D-визуализацией и методические материалы для школьников.'),
         ('Grant project: a platform for learning machine vision', None, 'Grant', 'A mobile platform with neural networks for traffic sign recognition, a test track with 3D visualisation, and teaching materials for school students.')),
        ('competition', 'personal', 2021,
         ('Всероссийский конкурс Intel AI for Youth', 'Intel AI for Youth', '1 место', 'Учебный кейс по машинному зрению с 3D-камерой для беспилотного автомобиля на Raspberry Pi.'),
         ('Intel AI for Youth national contest', 'Intel AI for Youth', '1st place', 'A teaching case on machine vision with a 3D camera for a self-driving car on Raspberry Pi.')),
        ('competition', 'personal', 2021,
         ('Всероссийский конкурс «ПедКом»', 'ПедКом', '1 место', 'Номинация «Инновационные технологии в образовании»: урок информатики с дополненной реальностью.'),
         ('PedKom national contest', 'ПедКом', '1st place', 'Innovative technologies in education: a computer science lesson with augmented reality.')),
        ('certification', 'personal', 2020,
         ('Мастер-тренер Intel AI for Youth', 'Intel AI for Youth', 'Мастер-тренер', 'Сертифицированный мастер-тренер программы и педагог Лицея Академии Яндекса.'),
         ('Intel AI for Youth master trainer', 'Intel AI for Youth', 'Master trainer', 'Certified master trainer of the programme and teacher at Yandex Academy Lyceum.')),
        ('competition', 'personal', 2018,
         ('Хакатон StarLine «Умный автомобиль»', 'Фестиваль «Робофинист»', '4 место', 'Участие в команде педагогов на международном фестивале робототехники.'),
         ('StarLine Smart Car hackathon', 'Robofinist international festival', '4th place', 'Competed as part of a team of teachers at an international robotics festival.')),
        ('competition', 'students', 2022,
         ('Всероссийский конкурс проектов Intel AI for Youth', 'Intel AI for Youth', '2 место', 'Проект «Eye»: компьютерное зрение отслеживает перемещение людей в здании.'),
         ('Intel AI for Youth national project contest', 'Intel AI for Youth', '2nd place', 'Project Eye uses computer vision to track people moving through a building.')),
        ('competition', 'students', 2020,
         ('First Russia Robotics Competition, Москва', 'FIRST Russia', '1 место', 'Проект «Умный дом» в направлении FIRST LEGO League Junior.'),
         ('First Russia Robotics Competition, Moscow', 'FIRST Russia', '1st place', 'Smart Home project in FIRST LEGO League Junior.')),
        ('competition', 'students', 2019,
         ('«Московские мастера» по стандартам WorldSkills', 'Московские мастера', '3 место', 'Компетенция «Мобильная робототехника».'),
         ('Moscow Masters (WorldSkills standards)', 'Moscow Masters', '3rd place', 'Mobile Robotics skill.')),
        ('competition', 'students', 2018,
         ('Международный конкурс «ПРИЗМА»', 'ПРИЗМА', 'Победа', 'Проект перчатки для незрячих и слабовидящих людей.'),
         ('PRIZMA international contest', 'PRIZMA', 'Winner', 'A glove designed for blind and visually impaired people.')),
        ('competition', 'students', 2017,
         ('Национальный этап Eurobot', 'Eurobot', '2 место', 'Робот-сборщик ресурсов на Arduino Mega.'),
         ('Eurobot national stage', 'Eurobot', '2nd place', 'A resource-collecting robot built on Arduino Mega.')),
        ('competition', 'students', 2017,
         ('Всероссийский конкурс «ШУСТРИК», номинация «Космос»', 'ШУСТРИК', '1 место', 'Исследовательский комплекс: ровер на Arduino и станция, управляемая из Android-приложения.'),
         ('SHUSTRIK national contest, Space category', 'SHUSTRIK', '1st place', 'Research complex with an Arduino rover and a station controlled from an Android app.')),
        ('expertise', 'personal', None,
         ('Судья и эксперт робототехнических соревнований', 'Робофест, RRO, SK Junior Challenge', 'Эксперт', 'Судья и эксперт конкурсов проектов и робототехнических соревнований.'),
         ('Judge and expert at robotics competitions', 'Robofest, RRO, SK Junior Challenge', 'Expert', 'Judge and expert at project contests and robotics competitions.')),
    ]
    achievement_ids = []
    achievement_values = []
    translation_values = []
    for order, (category, scope, year, ru, en) in enumerate(achievement_rows):
        achievement_id = UUID(f'10000000-0000-4000-8000-{order + 1:012d}')
        achievement_ids.append(achievement_id)
        achievement_values.append({
            'id': achievement_id, 'category': category, 'scope': scope, 'year': year,
            'source_url': None, 'image_url': None, 'order': order,
            'is_featured': order < 3, 'is_published': True,
            'created_at': created_at, 'updated_at': created_at,
        })
        for language_order, (lang, data) in enumerate((('ru', ru), ('en', en)), start=1):
            title, organization, result, description = data
            translation_values.append({
                'id': UUID(f'20000000-0000-4000-8000-{order + 1:010d}{language_order:02d}'),
                'achievement_id': achievement_id, 'lang': lang, 'title': title,
                'organization': organization, 'result': result,
                'short_description': None, 'description': description,
            })
    op.bulk_insert(achievement_table, achievement_values)
    op.bulk_insert(achievement_translation_table, translation_values)

    page_id = UUID('30000000-0000-4000-8000-000000000001')
    page_table = sa.table(
        'mentoring_pages', sa.column('id', sa.Uuid()), sa.column('slug', sa.String()),
        sa.column('is_published', sa.Boolean()), sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    page_translation_table = sa.table(
        'mentoring_page_translations', sa.column('id', sa.Uuid()), sa.column('page_id', sa.Uuid()),
        sa.column('lang', lang_enum), sa.column('kicker', sa.String()),
        sa.column('title_start', sa.String()), sa.column('title_accent', sa.String()),
        sa.column('lead', sa.Text()),
    )
    op.bulk_insert(page_table, [{
        'id': page_id, 'slug': 'mentoring', 'is_published': True,
        'created_at': created_at, 'updated_at': created_at,
    }])
    page_copy = {
        'ru': ('Наставничество', 'Исследования, конкурсы', 'и команды учеников', 'Опыт руководства кафедрой дизайна и технологии Международной гимназии «Сколково»: учебные программы по ИИ, программированию и робототехнике, инженерная лаборатория и десятки ученических проектов — от роботов до нейросетей.'),
        'en': ('Mentoring', 'Research, awards', 'and student teams', 'Experience heading the Design & Technology department at the Skolkovo International Gymnasium: curricula in AI, programming and robotics, an engineering lab and dozens of student projects — from robots to neural networks.'),
    }
    op.bulk_insert(page_translation_table, [
        {
            'id': UUID(f'31000000-0000-4000-8000-{language_order:012d}'),
            'page_id': page_id, 'lang': lang, 'kicker': data[0],
            'title_start': data[1], 'title_accent': data[2], 'lead': data[3],
        }
        for language_order, (lang, data) in enumerate(page_copy.items(), start=1)
    ])

    metric_rows = [
        ('projects', '30+', 'проектов учеников', 'student projects'),
        ('prizes', '20', 'призёров и победителей конкурсов', 'competition prize winners'),
        ('programs', '10+', 'учебных программ', 'curricula'),
    ]
    metric_ids = [UUID(f'32000000-0000-4000-8000-{index:012d}') for index in range(1, 4)]
    metric_table = sa.table(
        'mentoring_metrics', sa.column('id', sa.Uuid()), sa.column('page_id', sa.Uuid()),
        sa.column('key', sa.String()), sa.column('value', sa.String()), sa.column('order', sa.Integer()),
    )
    metric_translation_table = sa.table(
        'mentoring_metric_translations', sa.column('id', sa.Uuid()),
        sa.column('metric_id', sa.Uuid()), sa.column('lang', lang_enum), sa.column('label', sa.String()),
    )
    op.bulk_insert(metric_table, [
        {'id': metric_ids[index], 'page_id': page_id, 'key': row[0], 'value': row[1], 'order': index}
        for index, row in enumerate(metric_rows)
    ])
    op.bulk_insert(metric_translation_table, [
        {
            'id': UUID(f'33000000-0000-4000-8000-{metric_index:010d}{language_order:02d}'),
            'metric_id': metric_ids[metric_index - 1], 'lang': lang, 'label': label,
        }
        for metric_index, row in enumerate(metric_rows, start=1)
        for language_order, (lang, label) in enumerate((('ru', row[2]), ('en', row[3])), start=1)
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentoring_metric_translations_metric_id'), table_name='mentoring_metric_translations')
    op.drop_table('mentoring_metric_translations')
    op.drop_index(op.f('ix_article_tocs_parent_id'), table_name='article_tocs')
    op.drop_index(op.f('ix_article_tocs_article_id'), table_name='article_tocs')
    op.drop_table('article_tocs')
    op.drop_index(op.f('ix_project_translations_project_id'), table_name='project_translations')
    op.drop_table('project_translations')
    op.drop_index(op.f('ix_mentoring_page_translations_page_id'), table_name='mentoring_page_translations')
    op.drop_table('mentoring_page_translations')
    op.drop_index(op.f('ix_mentoring_metrics_page_id'), table_name='mentoring_metrics')
    op.drop_table('mentoring_metrics')
    op.drop_index(op.f('ix_experience_translations_experience_id'), table_name='experience_translations')
    op.drop_table('experience_translations')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_project_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_achievement_translations_achievement_id'), table_name='achievement_translations')
    op.drop_table('achievement_translations')
    op.drop_table('projects')
    op.drop_table('mentoring_pages')
    op.drop_index('ix_feedback_messages_status', table_name='feedback_messages')
    op.drop_index('ix_feedback_messages_email_status', table_name='feedback_messages')
    op.drop_index('ix_feedback_messages_created_at', table_name='feedback_messages')
    op.drop_table('feedback_messages')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_achievements_scope'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_category'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
    # Тип enum создаётся вместе с таблицами переводов, но drop_table его не удаляет
    postgresql.ENUM(name='langenum').drop(op.get_bind(), checkfirst=True)
