"""add responsibilities for experience

Revision ID: be2945938b7e
Revises: 24f18d5979ed
Create Date: 2025-07-15 00:57:42.619001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2945938b7e'
down_revision: Union[str, Sequence[str], None] = '24f18d5979ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience_translations', sa.Column('responsibilities', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience_translations', 'responsibilities')
    # ### end Alembic commands ###
