"""initial migration

Revision ID: cc4f468102d3
Revises: 
Create Date: 2025-07-14 11:57:13.054643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4f468102d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stack', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('demo_url', sa.String(length=255), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_project_id'), 'articles', ['project_id'], unique=True)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_table('experience_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'en', name='langenum'), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'lang', name='_experience_lang_uc')
    )
    op.create_index(op.f('ix_experience_translations_experience_id'), 'experience_translations', ['experience_id'], unique=False)
    op.create_table('project_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'en', name='langenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'lang', name='_project_lang_uc')
    )
    op.create_index(op.f('ix_project_translations_project_id'), 'project_translations', ['project_id'], unique=False)
    op.create_table('article_tocs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('anchor', sa.String(length=255), nullable=True),
    sa.Column('order', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['article_tocs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_tocs_article_id'), 'article_tocs', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_tocs_parent_id'), 'article_tocs', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_tocs_parent_id'), table_name='article_tocs')
    op.drop_index(op.f('ix_article_tocs_article_id'), table_name='article_tocs')
    op.drop_table('article_tocs')
    op.drop_index(op.f('ix_project_translations_project_id'), table_name='project_translations')
    op.drop_table('project_translations')
    op.drop_index(op.f('ix_experience_translations_experience_id'), table_name='experience_translations')
    op.drop_table('experience_translations')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_project_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_table('projects')
    op.drop_table('experiences')
    # ### end Alembic commands ###
