"""fix fields

Revision ID: 78dd434c8dd6
Revises: f5ab6f5e7ad6
Create Date: 2025-10-11 19:12:54.006263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78dd434c8dd6'
down_revision: Union[str, Sequence[str], None] = 'f5ab6f5e7ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('posts', sa.Column('url', sa.String(length=500), nullable=True))
    op.drop_column('posts', 'cover_url')
    op.drop_column('posts', 'content_html')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_html', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('cover_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('posts', 'url')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
