name: Build Auth Service

run-name: "Build Auth Service for ${{ github.ref_name }} by ${{ github.actor }}"

on:
  push:
    branches:
      - main
    paths:
      - 'services/auth/**'
      - '.github/workflows/auth-build.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          echo "Тесты пока отключены. Возвращаем успешный статус."

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Export ENV_VARS
        run: |
          printf "%s\n" "${{ secrets.ENV_AUTH_VARS }}" | while IFS= read -r line; do
            if [[ ! -z "$line" && "$line" != \#* ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done

      - name: Build and push image
        run: |
          docker build \
            -t aleksioprime/aledev-auth:latest ./services/auth/app

          docker push aleksioprime/aledev-auth:latest
