name: Build Main App

run-name: "Build Main App for ${{ github.ref_name }} by ${{ github.actor }}"

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/main-build.yml'
      - '*'
    paths-ignore:
      - 'README.md'
      - 'readme.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          echo "Тесты пока отключены. Возвращаем успешный статус."

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Export ENV_VARS
        run: |
          printf "%s\n" "${{ secrets.ENV_VARS }}" | while IFS= read -r line; do
            if [[ ! -z "$line" && "$line" != \#* ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done

      - name: Build and push image
        run: |
          docker build --target prod \
            --build-arg VITE_LOGGING=0 \
            --build-arg VITE_AUTH_URL=$VITE_AUTH_URL \
            -t aleksioprime/aledev-frontend:latest ./frontend

          docker push aleksioprime/aledev-frontend:latest
