name: Deploy Portfolio Service

run-name: "Deploy Portfolio Service for ${{ github.ref_name }} by ${{ github.actor }}"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

            mkdir -p ~/aledev/services/portfolio
            cd ~/aledev/services/portfolio

            echo "${{ secrets.ENV_PORTFOLIO_VARS }}" > ~/aledev/services/portfolio/.env
            echo "Файл .env загружен на сервер"

            curl -o ~/aledev/services/portfolio/docker-compose.prod.yaml https://raw.githubusercontent.com/aleksioprime/aledev/main/services/portfolio/docker-compose.prod.yaml

            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            docker compose -f docker-compose.prod.yaml down
            docker compose -f docker-compose.prod.yaml pull
            docker compose -f docker-compose.prod.yaml up -d --remove-orphans

            docker image prune -a -f
            echo "Portfolio сервис обновлён!"

          EOF
